services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_queue
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DOCKER_IMAGE=python:3.10-slim
      - SHARED_PATH_ON_HOST=sandbox_data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sandbox_data:/tmp/shared_jobs
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  sandbox_data:
    name: sandbox_data